name: guten_read
description: "A Flutter application that analyzes books from Project Gutenberg to extract and visualize character relationships using AI."
publish_to: 'none'  # Prevents accidental publishing to pub.dev
version: 1.0.0+1

# Environment Constraints
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UI
  flutter_screenutil: ^5.9.3
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.1
  
  # Networking
  dio: ^5.8.0+1
  
  # Utilities
  url_launcher: ^6.3.2
  intl: ^0.20.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  
  # Code Quality
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.6.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true  # Enables Flutter Web optimizations

  # Assets
  assets:
    - .env
